sudo: false
language: python
os:
  - linux
python:
  - "3.6"
branches:
  only:
    - main
script:
  - export FONT=data/test/Mada-Regular.ttf # sample font file for testing purposes
  - export QUIET=" 2>&1 > long_output.txt && cat long_output.txt | tail -n20"
  - python setup.py install
  - eval pyfontaine 0x0061 $QUIET
  - eval pyfontaine U+C480 U+C481 $FONT $QUIET
  - eval pyfontaine --xml $FONT $QUIET
  - eval pyfontaine --json $FONT $QUIET
  - eval pyfontaine --csv $FONT $QUIET
  - eval pyfontaine --wiki $FONT $QUIET
  - eval pyfontaine U+C480 U+C481 $FONT $QUIET
  - eval pyfontaine --set africaan,adobe_latin_3 $FONT $QUIET
  - eval pyfontaine --missing --set adobe_latin_3 $FONT $QUIET
  - eval pyfontaine --collections all $FONT $QUIET # default
  - eval pyfontaine --collections pyfontaine $FONT $QUIET
  - eval pyfontaine --collections uniblocks $FONT $QUIET
  - eval pyfontaine --collections extensis $FONT $QUIET
  - eval pyfontaine --collections fontconfig $FONT $QUIET
  - eval pyfontaine --collections cldr $FONT $QUIET
  - eval pyfontaine --collections subsets $FONT $QUIET
